### ISSUE TITLE
Unable to start the app

### ISSUE THREAD

**Issue by sah-anshu** [delitamakanda/dopejob#8]
HI, 

I am unable to start the app.  Even the page I am able to see on your DEMO Link. 
https://dopejob.herokuapp.com/ 

![Screen Shot](https://user-images.githubusercontent.com/9985291/76139825-25857000-607a-11ea-9683-1c2bf38afcfb.png)

Please advise what I am doing wrong. 

-Thanks
A

**Comment by delitamakanda** [comment]
hi,

sorry for inconvenience. 
Serve this project in two consoles one for django `python3 manage.py runserver ` and another for react with cmd `npm start`
